---
title: "weiboVolumn"
author: "lushi"
date: "26/01/2019"
output: html_document
---

```{r setup, include=FALSE}
library(data.table)
library(ggplot2)

```


#This script plots weibo volumn in 24 hours

clean data
```{r cars}
cesd<- read.csv('~/phd_work/depression dessertation/data/depression_fix_nohis.csv')
file<- read.csv('~/phd_work/depression dessertation/data/Weibo_all_clean2.csv') 
file2 <- file
# fix time formate
file2$time <- gsub("\\来自.*", "", file2$time)
# select time without year (2016)
addY <- file2[file2$time %like% "月", ]
addY$time <- gsub("月", "-", addY$time)
addY$time <- gsub("日", "", addY$time)
addY$time <- paste0("2016-", addY$time)

#merge 2016 data
file2$time <- gsub("\\来自.*", "", file2$time)
#convert time to integer
add2016 <- file2[- grep("月", file2$time),]
allTime <- rbind(add2016, addY)

#the date we collect the post was 2016-09-05 add date to today
today <- allTime[allTime$time %like% "今天", ]
today$time <- paste(today$time, sep = "", ":00")
today$time <- gsub("今天", "2016-09-05", today$time)  
allTime2 <- allTime[- grep("今天", allTime$time),]
allTime3 <- rbind(allTime2, today)
allTime3 <- allTime3[- grep("分钟", allTime3$time),]
#now remove year and second
allTime3 <- allTime3[-grep("/", allTime3$time),]
allTime3$time <- as.character(allTime3$time)
allTime4 <- allTime3

allTime4$time <- lapply(strsplit(allTime4$time, " "), tail, 1)
allTime4$time <- as.character(allTime4$time)
allTime4$time <- lapply(strsplit(allTime4$time, ":"), head, 1)

#aggregate volumn according to time
allTime4$time <- as.numeric(allTime4$time)
count <- data.frame(table(allTime4$time))

```

remember to set cut off points for the function
```{r pressure, echo=FALSE}

#separate high and l group
#cesd sum
cesd$cesd_sum <- rowSums(cesd[,3:13])
all <- merge(allTime4,cesd, by = 'userid')

getData <- function(mydata, cutoff) {
  high <- all[all$cesd_sum > cutoff, ]
  count_h <- data.frame(table(high$time))
  count_h$Freq <- (count_h$Freq/length(unique(high$userid)))
  low <- all[all$cesd_sum < cutoff, ]
  
  #we can change the low group and plot it again 
  count_l <- data.frame(table(low$time))
  count_l$Freq <- (count_l$Freq/length(unique(low$userid)))
  
  #merge plots
  h_l <- merge(count_l, count_h, by = 'Var1')
  h_l$Var1 <- as.numeric(as.character(h_l$Var1))
  return (h_l)

}

myplot <- function(mydata){
  p <- ggplot(data=h_l, aes(x=Var1)) + 
  #  geom_line(colour="red", linetype="dashed", size=1.5) + 

    geom_point(aes(y = Freq.x, colour="low"),size=3)+
    geom_line(aes(y = Freq.x, colour="low"),size=1)+
    geom_line(aes(y = Freq.y, colour="high"), size=1)+
    geom_point(aes(y = Freq.y, colour="high"), size=3)+
    xlab("Time") + ylab("Post volume/day")+
    theme(text = element_text(size=15), axis.text.x = element_text(size= 15, angle=90, hjust=1),
          axis.text.y = element_text(size= 15, angle=90, hjust=1))
    
  
  return (p)
}

h_l <- getData(all, 22)
myplot(h_l)

##t test for two groups in day time and night time
dayTime <- h_l[h_l$Var1 <= 18 & h_l$Var1 >= 8, ] 
t.test(dayTime$Freq.x,dayTime$Freq.y)
mean(dayTime$Freq.x)
mean(dayTime$Freq.y)

sd(dayTime$Freq.x)
sd(dayTime$Freq.y)

nightTime <- h_l[h_l$Var1 > 18 | h_l$Var1 < 8, ] 
t.test(nightTime$Freq.x,nightTime$Freq.y)

#peak time compare with 8PM
peakTime <- h_l[h_l$Var1 >= 20 & h_l$Var1 <= 24, ] 
mean(peakTime$Freq.x)
mean(peakTime$Freq.y)
#mean - 8PM amount
(mean(peakTime$Freq.x) - 2.87)/2.87 #1.28
(mean(peakTime$Freq.y) - 2.31)/2.31 #1.48
#over the past three years, each person in the H group generate 28 weibo at day time, whereas, each person in the l group generate 
#34, l group has 16% more weibo than the h group during the daytime. h group generate similar amount of weibo as with l group from 
#19 to 8 o'clock

#from 8 to 17 o'clock, low group (33.6) has more Weibo than h(28) group 
high <- all[all$cesd_sum > 22, ]
count_h <- data.frame(table(high$time))
count_h$Freq <- count_h$Freq/length(unique(high$userid))
low <- all[all$cesd_sum <= 22, ]

#we can change the low group and plot it again 
count_l <- data.frame(table(low$time))
count_l$Freq <- count_l$Freq/length(unique(low$userid))
count_h$Var1 <- as.numeric(count_h$Var1)
h_daytime <- count_h[count_h$Var1 >= 8 & count_h$Var1 <= 18, ]
#h group, number of posts a day
sum(h_daytime$Freq) #28

count_l$Var1 <- as.numeric(count_l$Var1)
l_daytime <- count_l[count_l$Var1 >= 8 & count_l$Var1 <= 18, ]
#l group, number of posts a day
sum(l_daytime$Freq) #36

```

